### ISSUE TITLE
Add schedule option to settings

### ISSUE THREAD

**Issue by sojusnik** [ionutbortis/gnome-bedtime#1]
Would be great to have this feature in order to easily adjust when the desktop should grey out. Not everybody is into scripting, crontab etc. so I think that this feature would be very appreciated.

You've mentioned [Night Theme Switcher](https://extensions.gnome.org/extension/2236/night-theme-switcher/), but why use another extension, if a manual schedule would perfectly fit into this extension's settings?

Additionally, the purpose of the linked extension is to automatically switch to an appropriate theme for working at the evening or at night, while your extension's purpose is to move the user to stop working altogether after a certain time. So using the linked extension for scheduling your extension isn't really possible, if one has a need for those two use-cases.

**Comment by ionutbortis** [comment]
You're right, this definitely needs a settings UI for manual scheduling. I also have some other features in mind, but maybe for later versions. 
The manual scheduling plus the the ability to preserve the grayscale screen when logged out, etc, will be implemented in the next version. 

Thank you for your input!

**Comment by quasipedia** [comment]
You seem to be already in agreement here: I can only support this wholeheartedly.

**Comment by ivanmood0** [comment]
First of all, I would like to thank you for the wonderful expansion, but as mentioned above, control of expansion is inconvenient, is required the tray icon (on/off) for management, and even better to be able to add icon into the system menu, like how it is implemented in the extension "GSConnect", to make it look like it's built into the system itself, especially since you do not always use it. And it would be perfect, if all the inscriptions in the extension settings or in the extension menu itself, would be contained in a separate file (which will simply connect). This would allow to translate it ourselves into the language we need and possibly later, added support for multiple languages default to the expansion.

**Comment by ionutbortis** [comment]
> First of all, I would like to thank you for the wonderful expansion, but as mentioned above, control of expansion is inconvenient, is required the tray icon (on/off) for management, and even better to be able to add icon into the system menu, like how it is implemented in the extension "GSConnect", to make it look like it's built into the system itself, especially since you do not always use it. And it would be perfect, if all the inscriptions in the extension settings or in the extension menu itself, would be contained in a separate file (which will simply connect). This would allow to translate it ourselves into the language we need and possibly later, added support for multiple languages default to the expansion.

Thank you for the suggestions! 
I added two separate issues:
https://github.com/ionutbortis/gnome-bedtime/issues/2
https://github.com/ionutbortis/gnome-bedtime/issues/3

#2 will probably be implemented in the next version.

**Comment by ivanmood0** [comment]
> > Перш за все, я хотів би подякувати вам за чудове розширення, але, як згадувалося вище, контроль розширення незручний, для управління потрібен значок лотка (увімкнено / вимкнено), а ще краще, щоб мати можливість додавати піктограму в системне меню, наприклад, як це реалізовано в розширенні "GSConnect", щоб виглядати так, ніби воно вбудоване в саму систему, тим більше, що ви не завжди ним користуєтесь. І було б ідеально, якби всі написи в налаштуваннях розширення або в самому меню розширення містилися в окремому файлі (який просто підключиться). Це дозволило б самостійно перекласти його на потрібну нам мову і, можливо, пізніше, додало б підтримку кількох мов за замовчуванням до розширення.
> 
> Дякую за пропозиції!
> Я додав два окремих питання:
> [# 2 ](https://github.com/ionutbortis/gnome-bedtime/issues/2)
> [# 3](https://github.com/ionutbortis/gnome-bedtime/issues/3)
> 
> [№2](https://github.com/ionutbortis/gnome-bedtime/issues/2) , ймовірно, буде реалізовано в наступній версії.

Oh, that's great. I look forward to updating.

**Comment by ivanmood0** [comment]
> > First of all, I would like to thank you for the wonderful expansion, but as mentioned above, control of expansion is inconvenient, is required the tray icon (on/off) for management, and even better to be able to add icon into the system menu, like how it is implemented in the extension "GSConnect", to make it look like it's built into the system itself, especially since you do not always use it. And it would be perfect, if all the inscriptions in the extension settings or in the extension menu itself, would be contained in a separate file (which will simply connect). This would allow to translate it ourselves into the language we need and possibly later, added support for multiple languages default to the expansion.
> 
> Thank you for the suggestions!
> I added two separate issues:
> #2
> #3
> 
> #2 will probably be implemented in the next version.

Oh, that's great. I look forward to updating.

**Comment by ionutbortis** [comment]
Hello everyone!

I'm happy to announce that [Version 2 Release Candidate 1 ](https://github.com/ionutbortis/gnome-bedtime/releases/download/v2-rc1/gnome-bedtime_v2-rc1.zip) is out and ready for manual installation!

You can download the [gnome-bedtime_v2-rc1.zip](https://github.com/ionutbortis/gnome-bedtime/releases/download/v2-rc1/gnome-bedtime_v2-rc1.zip) zip file and manually install it to your extension folder:

`wget https://github.com/ionutbortis/gnome-bedtime/releases/download/v2-rc1/gnome-bedtime_v2-rc1.zip` 
(or manually download via browser and run the next commands from the download folder)

`extension_home=~/.local/share/gnome-shell/extensions/gnomebedtime@ionutbortis.gmail.com`

`rm -rf $extension_home/* && unzip gnome-bedtime_v2-rc1.zip -d $extension_home`

Hit ALT+F2, type 'r' and press Enter to restart the gnome shell. 
Then go to the Extensions app, enable Gnome Bedtime and now you can change it's settings to your liking. Yay! 

This version works properly on my machine, but any testing done on other systems is much appreciated!

If everything is fine I will merge the version 2 changes to the main branch, create a final v2 release and submit the package to the gnome extensions website.

Thanks!
