### ISSUE TITLE
Pixelation and artefacts of windows in overview mode

### ISSUE THREAD

**Issue by ivanmood0** [ionutbortis/gnome-bedtime#5]
After installing the extension (version 2.0) in overview mode, when 3 or more applications are running, there is a noticeable pixelation and artefacts of windows.

Ubuntu 20.04
Gnome 3.36
![bugg](https://user-images.githubusercontent.com/79835684/113778784-7eb84b00-9735-11eb-8c5e-8f9635f18f29.png)

**Comment by ionutbortis** [comment]
Thank you for reporting this! 

The issue should be fixed now in the latest release https://github.com/ionutbortis/gnome-bedtime/releases/tag/v2.1
You can also try it out by using the manual installation guide from the project homepage.

If the Bedtime Mode is Off then the overview apps should look fine now, not weird pixelation and artifacts. 

When the Bedtime Mode is On there is some pixelation but I believe that's just how the way Gnome applies the Desaturation Effect. Nothing I can do about that. 

When the grayscale effect is on you should not use that much your PC, anyways, so I guess is acceptable.

**Comment by ivanmood0** [comment]
> Thank you for reporting this!
> 
> The issue should be fixed now in the latest release https://github.com/ionutbortis/gnome-bedtime/releases/tag/v3.0
> You can also try it out by using the manual installation guide from the project homepage.
> 
> If the Bedtime Mode is Off then the overview apps should look fine now, not weird pixelation and artifacts.
> 
> When the Bedtime Mode is On there is some pixelation but I believe that's just how the way Gnome applies the Desaturation Effect. Nothing I can do about that.
> 
> When the grayscale effect is on you should not use that much your PC, anyways, so I guess is acceptable.

Thank you for your prompt response. I confirm that in v3.0 the problem of pixelation is not observed. As for pixelation in the Bedtime mode, it is not significant at all, because this mode will preferably be used only for a certain scenario, such as reading, etc.
